{
 "title": "Main SH Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ASSIGNATIONS CREATED TODAY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignations_created_today_ratio",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "PORTAL LIGHTS UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "max",
      "lastNotNull"
     ]
    }
   },
   "targets": [
    { "expr": "portal_lights_up_ratio", "legendFormat": "{{project_name}}" }
   ]
  },
  {
   "title": "PORTAL LIGHTS UP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "portal_lights_up_ratio", "legendFormat": "{{project_name}}" }
   ]
  },
  {
   "title": "ASSIGNATIONS CREATED",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "assignations_created_today_ratio",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "DEVICES UP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    { "expr": "devices_up_ratio", "legendFormat": "{{project_name}}" }
   ]
  }
 ]
}