apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-team
    receivers:
      - uid: email-team-receiver
        type: email
        settings:
          addresses: ${ALERT_EMAIL_ADDRESSES}
          singleEmail: false