apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: email-team
        matchers:
          - team=backend
        group_by:
          - alertname
          - project_uuid
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h